apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-poc-staging
  namespace: argocd-poc-staging
spec:
  project: default
  source:
    repoURL: 'https://github.com/DNXLabs/argocd-poc'
    path: staging/argocd-poc/templates
    targetRevision: deploy
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-poc-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true