apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: previews
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    repoURL: 'https://github.com/DNXLabs/argocd-poc.git'
    targetRevision: deploy
    path: apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: previews
  syncPolicy:
    automated:
      prune: true
      selfHeal: true