apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-poc-prod
  namespace: argocd-poc-prod
spec:
  project: default
  source:
    repoURL: https://github.com/DNXLabs/argocd-poc.git
    targetRevision: HEAD
    path: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-poc-prod