apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-poc-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DNXLabs/argocd-poc.git'
    targetRevision: deploy
    path: charts/argocd-poc
    helm:
      values: |
        image.tag: '{{.IMAGE_TAG}}'
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "alb"
            alb.ingress.kubernetes.io/scheme: "internet-facing"
            alb.ingress.kubernetes.io/group.name: argocd-poc
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-2:158947203889:certificate/44fe4011-802b-4fd1-a21e-1d4871975f10
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
          hosts:
            - host: 'argocd-poc.staging.labs2.dnx.host'
              paths: ['/*']
      version: v3
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-poc-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true