name: Publish Docker image master
on:
  push:
    branches:
    - master
jobs:
  push_to_ecr:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    container: dnxsolutions/aws:2.1.6-dnx1
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build, tag, and push image to Amazon public ECR
        env:
          ECR_REGISTRY: public.ecr.aws
          ECR_REPOSITORY: dnxsolutions/argocd-poc
        run: |
          apk add docker
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
  staging_deploy:
    name: Update staging deployment
    runs-on: ubuntu-latest
    needs: [push_to_ecr]
    container: dnxsolutions/docker-kube-tools:0.3.2
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: 'deploy'
      - name: Helm lint
        run: |
          helm lint ./charts/argocd-poc
      - name: Rendering template
        env:
          APP_ID: argocd-poc-staging
          HOSTNAME: argocd-poc.staging.labs2.dnx.host
        run: |
          cat template.yaml \
            | kyml tmpl \
              -e APP_ID \
              -v IMAGE_TAG=$GITHUB_SHA \
              -e HOSTNAME \
            | tee apps/$APP_ID.yaml
          git config --global user.name 'DNX Labs'
          git config --global user.email 'dnxlabs@users.noreply.github.com'
          git add ./apps/$APP_ID.yaml
          git commit -m "Updates staging deploy"
          git push origin deploy